language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
before_install:
- export DISPLAY=:99.0
- npm install -qg bower grunt-cli
- npm install -q
- bower install --force
- bower install --force